// auth.js
export const SAVE_ROLE_USER = 'SAVE_TOKEN'
export const SET_ROLE_USER = 'SET_ROLE_USER'
export const FETCH_ROLE_USER = 'FETCH_ROLE_USER'
export const FETCH_ROLE_USER_SUCCESS = 'FETCH_ROLE_USER_SUCCESS'
export const FETCH_ROLE_USER_FAILURE = 'FETCH_ROLE_USER_FAILURE'
export const UPDATE_ROLE_USER = 'UPDATE_ROLE_USER'
