// auth.js
export const SET_RECENT_UPDATES = 'SET_RECENT_UPDATES'
export const FETCH_RECENT_UPDATES = 'FETCH_RECENT_UPDATES'
export const FETCH_RECENT_UPDATES_SUCCESS = 'FETCH_RECENT_UPDATES_SUCCESS'
export const FETCH_RECENT_UPDATES_FAILURE = 'FETCH_RECENT_UPDATES_FAILURE'
export const UPDATE_RECENT_UPDATES = 'UPDATE_RECENT_UPDATES'
