// auth.js
export const SAVE_NOTIFICATION = 'SAVE_TOKEN'
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION'
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS'
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE'
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'
