// auth.js
export const SAVE_ORDER_DETAILS = 'SAVE_TOKEN'
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS'
export const FETCH_ORDER_DETAILS = 'FETCH_ORDER_DETAILS'
export const FETCH_ORDER_DETAILS_SUCCESS = 'FETCH_ORDER_DETAILS_SUCCESS'
export const FETCH_ORDER_DETAILS_FAILURE = 'FETCH_ORDER_DETAILS_FAILURE'
export const UPDATE_ORDER_DETAILS = 'UPDATE_ORDER_DETAILS'
