// auth.js
export const SAVE_COMMENT = 'SAVE_TOKEN'
export const SET_COMMENT = 'SET_COMMENT'
export const FETCH_COMMENT = 'FETCH_COMMENT'
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS'
export const FETCH_COMMENT_FAILURE = 'FETCH_COMMENT_FAILURE'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
