// auth.js
export const SET_REQUESTS = 'SET_REQUESTS'
export const SET_REQUEST = 'SET_REQUEST'
export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS'
export const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE'
export const UPDATE_REQUEST = 'UPDATE_REQUEST'
