// auth.js
export const SAVE_SUPPLIER = 'SAVE_SUPPLIER'
export const FETCH_SUPPLIER = 'FETCH_SUPPLIER'
export const FETCH_SUPPLIER_SUCCESS = 'FETCH_SUPPLIER_SUCCESS'
export const FETCH_SUPPLIER_FAILURE = 'FETCH_SUPPLIER_FAILURE'
export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER'
